[package]
name = "solana-key-convert"
version = "0.1.0"
edition = "2021"

[dependencies]
bs58 = "0.5.1"
clap = { version = "4.5.7", features = ["derive"] }
eyre = "0.6.12"
serde_json = "1.0.117"
shellexpand = "3.1.0"
solana-sdk = "1.18.16"
